#!/bin/sh
set -e

case "$1" in
    remove|purge|deconfigure)
        systemctl stop fseventbridge.service >/dev/null 2>&1 || true
        systemctl disable fseventbridge.service >/dev/null 2>&1 || true
        ;;
esac

exit 0
